name: TEFAS Verisi Güncelle

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Her sabah 09:00'da çalışır (Türkiye saati)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu klonla
      uses: actions/checkout@v3

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Bağımlılıkları kur
      run: pip install -r requirements.txt

    - name: Python script'i çalıştır
      run: python tefas_scraper.py
