name: TEFAS Verisi Güncelle

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Her gün 09:00'da (UTC+3)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu klonla
      uses: actions/checkout@v3

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Gerekli paketleri kur
      run: pip install -r requirements.txt

    - name: Playwright bağımlılıklarını kur
      run: playwright install --with-deps

    - name: TEFAS verisini çek
      run: python tefas_scraper.py

    - name: Değişiklikleri commit et
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add tefas_gunluk.csv
        git commit -m "TEFAS verisi güncellendi: $(date)" || echo "No changes to commit"
        git push
